name: Fetch AQI Data

on:
  schedule:
    - cron: '0 * * * *'  # runs every hour
  workflow_dispatch:       # allows manual trigger from GitHub UI

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests google-cloud-bigquery python-dotenv db-dtypes

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Run fetch script
        run: python data_pipeline/fetch_aqi.py
        env:
          GCP_PROJECT_ID: nafasai-hackathon